export {
  ADMIN_ROLES,
  CRM_READ_ROLES,
  CRM_WRITE_ROLES,
  DOCUMENT_GENERATION_ROLES,
  DOCUMENT_READ_ROLES,
  ORDER_ROLES,
  PAYMENT_ROLES,
  PLATFORM_ROLES,
  getForbiddenRedirectPath,
  getPostLoginPath,
  getRoutePolicy,
  roleCanAccess,
  type AppRole,
  type RoutePolicy,
} from "@/server/auth/roles";
