export const privacyPolicyLabels = {
  websiteTypes: {
    company_site: "strona firmowa",
    online_store: "sklep internetowy",
    saas_app: "SaaS / aplikacja",
    blog_content: "blog / content",
    contact_form: "formularz kontaktowy",
    newsletter: "newsletter",
    user_account: "konto uzytkownika",
    payments: "platnosci",
    recruitment: "rekrutacja",
    other: "inne",
  },
  dataSubjectCategories: {
    website_users: "uzytkownicy strony",
    customers: "klienci",
    prospects: "potencjalni klienci",
    newsletter_subscribers: "subskrybenci newslettera",
    job_candidates: "kandydaci do pracy",
    contractors: "kontrahenci",
    account_users: "uzytkownicy konta",
  },
  processingPurposes: {
    contact_form: "obsluga formularza kontaktowego",
    orders: "obsluga zamowien",
    account: "zalozenie i utrzymanie konta",
    newsletter: "newsletter",
    own_marketing: "marketing wlasny",
    analytics: "analityka",
    complaints: "obsluga reklamacji",
    tax_accounting: "obowiazki podatkowo-ksiegowe",
    claims: "dochodzenie roszczen",
    recruitment: "rekrutacja",
  },
  legalBases: {
    contract: "wykonanie umowy",
    legal_obligation: "obowiazek prawny",
    legitimate_interest: "uzasadniony interes",
    consent: "zgoda",
    pre_contract: "dzialania przed zawarciem umowy",
  },
  recipientTools: {
    hosting: "hosting",
    email: "e-mail",
    payments: "platnosci",
    accounting: "ksiegowosc",
    crm: "CRM",
    analytics: "analityka",
    marketing: "marketing",
    forms: "narzedzia formularzy",
    it_providers: "dostawcy IT",
  },
  preferredContactChannels: {
    email: "e-mail",
    form: "formularz",
    postal: "poczta tradycyjna",
    phone: "telefon",
  },
} as const;

export type PrivacyPolicyLabelGroup = keyof typeof privacyPolicyLabels;
